### PR TITLE
Support typo-ed version of referrer for retro-compat

### PR DESCRIPTION
**Pull request by Wardormeur**

### CODE REVIEW

**Comment by DanielBrierton** [comment]
@Wardormeur Superceded and can be closed, right?

**Comment by Wardormeur** [comment]
Err.. no, necessary as it replaces v2 with /

**Comment by DanielBrierton** [comment]
My bad. Also, didn't mean to actually close it. Whoops!

**Comment by Wardormeur** [comment]
3 files, 3 conflicts :'( I'll have a look today, requires https://github.com/CoderDojo/cp-zen-platform/pull/1254

**Pull request merged**
