### PR TITLE
Make the calendar subscribe link blue

### PR DESCRIPTION
**Pull request by CurtisHughes**
Calendar subscribe link is now blue.

[Issue-#1256](https://github.com/CoderDojo/community-platform/issues/1256)

Example:
image

### CODE REVIEW

**Comment by Wardormeur** [comment]
Hey @CurtisHughes , apologies for coming back to you so late.
Could you move `hover` 's color into its own variable in `variables.less`?
I've been looking through the codebase and have been unable to find it as well.
Otherwise :+1: 
Does it reflect what you thought @niccokunzmann ?

**Comment by niccokunzmann** [comment]
Yes, it is blue, I am very fine with it!

**Comment by CurtisHughes** [comment]
Hey @Wardormeur no worries 😄. I added the on-hover color variable to the `variables.less` file. Let me know if you have any other suggestions 👍.

**Comment by Wardormeur** [comment]
Sorry for being a bit slow
Looks all good to me, thanks a lot @CurtisHughes

**Pull request merged**
